import { $TSContext } from 'amplify-cli-core';
import { printer } from 'amplify-prompts';
import AmplifyUIBuilder from 'aws-sdk/clients/amplifyuibuilder';
import { AmplifyStudioClient } from '../clients';
import { isFormDetachedFromModel, isFormSchemaCustomized, shouldRenderComponents } from '../commands/utils';

/**
 * Handles showing a warning for detached forms pre-push.
 */
export const prePushHandler = async (context: $TSContext): Promise<void> => {
  if (!(await shouldRenderComponents(context))) {
    return;
  }
  const studioClient = await AmplifyStudioClient.setClientInfo(context);
  const [formSchemas, localSchema] = await Promise.all([
    studioClient.listForms(),
    context.amplify.invokePluginMethod(
      context,
      'codegen',
      undefined,
      'getModelIntrospection',
      [context],
    ),
  ]);

  if (
    hasModels(localSchema)
  ) {
    printDetachedFormsWarning(formSchemas, localSchema);
  } else {
    printer.debug('Local schema not found');
    return;
  }
};

const printDetachedFormsWarning = (formSchemas: { entities: AmplifyUIBuilder.Form[] }, localSchema: {models: unknown}): void => {
  const models = localSchema.models;
  if (!models || typeof models !== 'object') {
    printer.debug('Models not found');
    return;
  }
  const modelNames = new Set(Object.keys(models));
  const detachedCustomForms: string[] = [];

  formSchemas.entities.forEach(form => {
    // Only show warnings for schema's that have customization, otherwise it's the same as
    // an autogenerated form.
    if (isFormDetachedFromModel(form, modelNames) && isFormSchemaCustomized(form)) {
      detachedCustomForms.push(form.name);
    }
  });

  if (detachedCustomForms.length > 0) {
    printer.warn(`The following form${detachedCustomForms.length === 1 ? '' : 's'} will no longer be available because the connected data model no longer exists: ${detachedCustomForms.join(', ')}`);
  }
};

const hasModels = (value: unknown): value is { models: unknown } => {
  return (
    typeof value === 'object'
    && value !== null
    && 'models' in value
  );
}